services:
  microros-esp32-builder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: microros_esp32_builder
    working_dir: /project
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - IDF_PATH=/opt/esp/idf
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"